#!/bin/bash/

### Anything in brackets is to be replaced by something else (not
### including the brackets.


Printing:
cl> lpr
 -P printername filename
 -o page-ranges=1-7,11-14 filename  



# find 
find -exec [command] {} \;
 # The command is executed on the results of find


rsync -a dir1/ dir2
# include the '/' if you want just the contents of dir1, not the
# entire directory


for f in *; do mv $f ${f//003/01}; done



